package com.kwad.sdk.core.config;

import com.bytedance.sdk.openadsdk.downloadnew.core.TTDownloadField;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.e;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import com.kwad.sdk.core.config.item.r;
import com.kwad.sdk.core.config.item.s;
import java.util.ArrayList;

/* loaded from: classes3.dex */
public final class c {
    public static k auc = new k("batchReportCatchLimit", 20);
    public static k aud = new k("exceptionCollectorSwitch", 1);
    public static k aue = new k("catchExceptionReportSwitch", 1);
    public static k auf = new k("mediaPlayerLogReport", 0);
    public static k aug = new k("didCopySwitch", 1);
    public static k auh = new k("enableHodor", 0);
    public static k aui = new k("speedLimitSwitch", 1);
    public static k auj = new k("speedLimitThreshold", 200);
    public static k auk = new k("ksNativeAdCustomSwitch", 0);
    public static k aul = new k("compoAndSoThreadPoolCoreSize", 0);
    public static k aum = new k("forceActivateAfterInstalled", 0);
    public static k aun = new k("spliceVideoInteractionType", 0);
    public static k auo = new k("feedLoadOptimizeType", 0);
    public static k aup = new k("feedLoadOptimizeExternalEnable", 0);
    public static k auq = new k("nativeAdSlideClickDisable", 0);
    public static k aur = new k("interstitialAdLoadProcessChange", 0);
    public static k aus = new k("interstitialAdActivityOpt", 0);
    public static k aut = new k("formAdExitInterceptSwitch", 0);
    public static k auu = new k("adLeaveConfirmSwitch", 0);
    public static k auv = new k("viewLandingPageTaskDuration", 15);
    public static k auw = new k("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d aux = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static o auy = new o("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d auz = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d auA = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static com.kwad.sdk.core.config.item.d auB = new com.kwad.sdk.core.config.item.d("commercialLoggerDeviceSwitch", false);
    public static k auC = new k("commercialLoggerSwitch", 1);
    public static r auD = new r("tkSoUrlV7a", "");
    public static r auE = new r("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d auF = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static m auG = new m("playerConfig", null);
    public static s auH = new s("pkgNameList", new ArrayList(0));
    public static s auI = new s("hostList", new ArrayList(0));
    public static s auJ = new s("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem auK = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c auL = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem auM = new InstallActivateReminderConfigItem();
    public static e auN = new e();
    public static l<Integer> auO = new l<>("adTKGrayConfig");
    public static p auP = new p("realtimeReportActions", "");
    public static q auQ = new q();
    public static k auR = new k("appInstallNoticeSecond", 0);
    public static k auS = new k("installFloatingLayerPostion", 0);
    public static k auT = new k("remindInstallStyle", 0);
    public static k auU = new k("remindInstallTime", 60);
    public static k auV = new k("watermarkKwaiIdSwitch", 0);
    public static k auW = new k("insertScreenV2Switch", 0);
    public static k auX = new k("insertScreenAutoPlaySwitch", 0);
    public static j auY = new j("insertScreenV2ShowConfig");
    public static k auZ = new k("environmentDetectEnable", 0);
    public static k ava = new k("simCardInfoEnable", 0);
    public static k avb = new k("baseStationEnable", 0);
    public static k avc = new k("sensorEventEnable2", 0);
    public static k avd = new k("lpAutoDownloadApkSwitch", 1);
    public static k ave = new k("autoDownloadUrlSwitch", 0);
    public static k avf = new k("insertScreenAdType", 0);
    public static k avg = new k("interstitialAutoCallAppCountDaily", 1);
    public static k avh = new k("mediaControlPlaySwitch", 1);
    public static r avi = new r("appStatusSoUrlV7a", "");
    public static r avj = new r("appStatusSoUrlV8a", "");
    public static r avk = new r("appStatusSoVersion", "");
    public static k avl = new k("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d avm = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static h avn = new h();
    public static com.kwad.sdk.core.config.item.d avo = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d avp = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static r avq = new r("TKSwitchExtra", "");
    public static com.kwad.sdk.core.config.item.d avr = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d avs = new com.kwad.sdk.core.config.item.d("TKJsonSubThread", true);
    public static com.kwad.sdk.core.config.item.d avt = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d avu = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static k avv = new k("forceActivate", 0);
    public static k avw = new k("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d avx = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static r avy = new r("nativeAndAnrDynamic", "");
    public static k avz = new k("kwaiAppVersionSwitch", 1);
    public static r avA = new r(TTDownloadField.TT_USERAGENT, com.kwad.sdk.core.network.p.getDefaultUserAgent());
    public static k avB = new k("biddingLogSwitch", 0);
    public static k avC = new k("forceActiveThreshold", 5);
    public static k avD = new k("forceActiveInterval", 3);
    public static k avE = new k("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d avF = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static g avG = new g("adExposureAreaPercent", 0.3f);
    public static g avH = new g("adExposureTime", -1.0f);
    public static g avI = new g("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d avJ = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d avK = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static k avL = new k("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d avM = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static com.kwad.sdk.core.config.item.d avN = new com.kwad.sdk.core.config.item.d("forceGetAudioFocus", false);
    public static k avO = new k("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d avP = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d avQ = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static o avR = new o("obiwanLogFilesDiskQuota", Long.valueOf(com.sigmob.sdk.downloader.core.download.g.f19256f));
    public static m avS = new m("logCommandResult", "", false);
    public static o avT = new o("validClickConvertTime", 1000L);
    public static com.kwad.sdk.core.config.item.d avU = new com.kwad.sdk.core.config.item.d("eplCommandSwitch", false);
    public static k avV = new k("playableAutoPlayEnable", 1);
    public static k avW = new k("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d avX = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d avY = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static k avZ = new k("weaponSwitch", 1);
    public static k awa = new k("kvModeV2", 0);
    public static i awb = new i();
    public static k awc = new k("idcRollbackInterval", 0);
    public static o awd = new o("currentServerTimeMs");
    public static k awe = new k("clientProofreadTimeErrorRangeHours", 100);
    public static g awf = new g("adTraceReportRate", 1.0f);
    public static k awg = new k("adTraceRepeatEnable", 0);
    public static k awh = new k("appHeartBeatInterval", 0);
    public static k awi = new k("insertShowPercent", 100);
    public static k awj = new k("adCacheCode", 0);
    public static r awk = new r("installTipsContentDesc", "");
    public static r awl = new r("installTipsPositiveActionDesc", "");
    public static r awm = new r("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d awn = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static r awo = new r("perfMonitorV2", "");
    public static k awp = new k("neoVideoAdaptStrategy", 1);
    public static k awq = new k("feedTKLoadTimeOut", 2500);
    public static com.kwad.sdk.core.config.item.d awr = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static k aws = new k("adImageLoaderCacheLimitSize", -1);
    public static com.kwad.sdk.core.config.item.d awt = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static k awu = new k("videoCacheOpt", 0);
    public static r awv = new r("ranger", "");
    public static r aww = new r("eplV1", "");
    public static r awx = new r("threadPoolPerfMonitor", "");
    public static r awy = new r("threadPoolParams", "");
    public static f awz = new f("crashUploadRate", Double.valueOf(1.0d));
    public static f awA = new f("adFeedWidthMinPercent", Double.valueOf(0.3d));
    public static com.kwad.sdk.core.config.item.d awB = new com.kwad.sdk.core.config.item.d("videoPerfMonitor", false);
    public static com.kwad.sdk.core.config.item.d awC = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d awD = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d awE = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", false);
    public static com.kwad.sdk.core.config.item.d awF = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);
    public static com.kwad.sdk.core.config.item.d awG = new com.kwad.sdk.core.config.item.d("usePolicy64LevelDisable", false);
    public static com.kwad.sdk.core.config.item.d awH = new com.kwad.sdk.core.config.item.d("tkReportInfoSwitch", false);
    public static k awI = new k("tubeRenderType", 0);
    public static k awJ = new k("useTKAdBrowse", 0);
    public static com.kwad.sdk.core.config.item.d awK = new com.kwad.sdk.core.config.item.d("enableMediaGetAdInfo", false);
    public static com.kwad.sdk.core.config.item.d awL = new com.kwad.sdk.core.config.item.d("ecExtInfoSwitch", false);
    public static r awM = new r("trackBlackUrlConfig", "");
    public static k awN = new k("tkMemCacheSize", 0);
    public static s awO = new s("preloadMemCacheTemplateIds", new ArrayList(0));
    public static k awP = new k("kGeoInfoConfig", 1);
    public static k awQ = new k("appMonitorSwitch", 0);
    public static k awR = new k("videoCacheErrorCallbackSwitch", 0);
    public static k awS = new k("tkErrorDetailCount", 1);
    public static k awT = new k("videoLaunchOptimiseSwitch", 0);
    public static k awU = new k("enableInitStartMode", 1);
    public static r awV = new r("localLogConfig", "");
    public static r awW = new r("adLogRetryConfig", "");
    public static n awX = new n("dpSchemeFlags");
    public static com.kwad.sdk.core.config.item.d awY = new com.kwad.sdk.core.config.item.d("feedAdBgTransparentSwitch");
    public static k awZ = new k("adRequestNum", 1);
    public static k axa = new k("carouselInterval", 30000);
    public static o axb = new o("packageInfoLimiter", 0L);
    public static com.kwad.sdk.core.config.item.d axc = new com.kwad.sdk.core.config.item.d("showOptimizedProgress");
    public static k axd = new k("optimizeProgressMethod", 0);

    public static void init() {
    }
}
