package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.InvokeBy;
import com.kwad.components.core.video.a.d;
import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.a.a;
import com.kwad.components.core.webview.jshandler.a.e;
import com.kwad.components.core.webview.jshandler.a.f;
import com.kwad.components.core.webview.jshandler.af;
import com.kwad.components.core.webview.jshandler.ag;
import com.kwad.components.core.webview.jshandler.ai;
import com.kwad.components.core.webview.jshandler.aj;
import com.kwad.components.core.webview.jshandler.am;
import com.kwad.components.core.webview.jshandler.an;
import com.kwad.components.core.webview.jshandler.ao;
import com.kwad.components.core.webview.jshandler.ar;
import com.kwad.components.core.webview.jshandler.as;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.au;
import com.kwad.components.core.webview.jshandler.aw;
import com.kwad.components.core.webview.jshandler.ax;
import com.kwad.components.core.webview.jshandler.az;
import com.kwad.components.core.webview.jshandler.bd;
import com.kwad.components.core.webview.jshandler.be;
import com.kwad.components.core.webview.jshandler.bf;
import com.kwad.components.core.webview.jshandler.bh;
import com.kwad.components.core.webview.jshandler.d;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.i;
import com.kwad.components.core.webview.jshandler.k;
import com.kwad.components.core.webview.jshandler.l;
import com.kwad.components.core.webview.jshandler.p;
import com.kwad.components.core.webview.jshandler.t;
import com.kwad.components.core.webview.jshandler.u;
import com.kwad.components.core.webview.jshandler.x;
import com.kwad.components.core.webview.tachikoma.a.h;
import com.kwad.components.core.webview.tachikoma.a.u;
import com.kwad.components.core.webview.tachikoma.a.x;
import com.kwad.sdk.i.a;
import com.kwad.sdk.kgeo.KGeoInfo;

/* loaded from: classes3.dex */
public final class cu {
    @InvokeBy(invokerClass = gc.class, methodId = "registerHolder")
    public static void Fe() {
        gc.Ff().put(u.b.class, new kb());
        gc.Ff().put(as.a.class, new bd());
        gc.Ff().put(ax.a.class, new lm());
        gc.Ff().put(d.b.class, new fg());
        gc.Ff().put(e.a.class, new ep());
        gc.Ff().put(a.C0508a.class, new iy());
        gc.Ff().put(h.a.class, new es());
        gc.Ff().put(ar.a.class, new ht());
        gc.Ff().put(x.a.class, new w());
        gc.Ff().put(x.a.class, new bk());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.b.class, new bi());
        gc.Ff().put(bh.a.class, new gb());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.d.class, new bo());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.h.class, new db());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.s.class, new jg());
        gc.Ff().put(ai.a.class, new lb());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.x.class, new lh());
        gc.Ff().put(l.a.class, new fm());
        gc.Ff().put(ao.a.class, new fx());
        gc.Ff().put(az.a.class, new gk());
        gc.Ff().put(k.a.class, new ev());
        gc.Ff().put(ag.a.class, new id());
        gc.Ff().put(com.kwad.components.core.k.a.class, new u());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.m.class, new gx());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.r.class, new jf());
        gc.Ff().put(d.b.class, new lg());
        gc.Ff().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new ac());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.q.class, new jd());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.o.class, new hr());
        gc.Ff().put(d.a.class, new lf());
        gc.Ff().put(ao.b.class, new fy());
        gc.Ff().put(au.a.class, new bp());
        gc.Ff().put(bd.a.class, new ll());
        gc.Ff().put(t.a.class, new kf());
        gc.Ff().put(be.a.class, new kn());
        gc.Ff().put(i.b.class, new eu());
        gc.Ff().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new ab());
        gc.Ff().put(bf.a.class, new fb());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.v.class, new la());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.p.class, new hz());
        gc.Ff().put(com.kwad.components.core.page.b.a.class, new gh());
        gc.Ff().put(af.a.class, new ic());
        gc.Ff().put(a.C0449a.class, new cc());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.j.class, new fz());
        gc.Ff().put(aw.a.class, new eb());
        gc.Ff().put(com.kwad.components.core.webview.a.c.class, new ho());
        gc.Ff().put(at.b.class, new bh());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.n.class, new hn());
        gc.Ff().put(p.a.class, new gv());
        gc.Ff().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new ge());
        gc.Ff().put(a.b.class, new dl());
        gc.Ff().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new ad());
        gc.Ff().put(g.a.class, new er());
        gc.Ff().put(i.a.class, new et());
        gc.Ff().put(am.a.class, new cx());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.e.class, new ca());
        gc.Ff().put(com.kwad.sdk.a.a.a.a.class, new fo());
        gc.Ff().put(com.kwad.components.core.n.c.b.class, new hl());
        gc.Ff().put(e.a.class, new ja());
        gc.Ff().put(f.a.class, new ch());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.i.class, new ew());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.l.class, new gi());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.g.class, new cl());
        gc.Ff().put(a.C0448a.class, new ak());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.a.class, new o());
        gc.Ff().put(com.kwad.components.core.n.c.d.class, new kz());
        gc.Ff().put(an.b.class, new ey());
        gc.Ff().put(at.a.class, new bg());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.w.class, new ld());
        gc.Ff().put(aj.a.class, new fd());
        gc.Ff().put(com.kwad.components.core.webview.a.b.class, new hm());
        gc.Ff().put(u.b.class, new jv());
        gc.Ff().put(KGeoInfo.class, new gd());
        gc.Ff().put(a.C0447a.class, new di());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.f.class, new ci());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.u.class, new ju());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.c.class, new bm());
        gc.Ff().put(h.b.class, new ib());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.t.class, new jh());
        gc.Ff().put(a.c.class, new he());
        gc.Ff().put(WebCardVideoPositionHandler.VideoPosition.class, new lj());
        gc.Ff().put(a.b.class, new iz());
        gc.Ff().put(com.kwad.components.core.webview.tachikoma.b.y.class, new lk());
        gc.Ff().put(f.a.class, new eq());
        gc.Ff().put(l.b.class, new fn());
    }
}
