package com.jd.ad.sdk.jad_lu;

import android.graphics.Bitmap;
import android.graphics.ColorFilter;
import android.graphics.PointF;
import android.graphics.Typeface;

/* loaded from: classes2.dex */
public interface jad_re {
    public static final Float jad_cn;
    public static final Float jad_do;
    public static final Float jad_ep;
    public static final Float jad_fq;
    public static final Float jad_gr;
    public static final Float jad_hs;
    public static final Float jad_hu;
    public static final Float jad_it;
    public static final Float jad_iv;
    public static final Float jad_ju;
    public static final Float jad_jw;
    public static final Float jad_kv;
    public static final PointF jad_kx;
    public static final Float jad_lw;
    public static final PointF jad_ly;
    public static final ColorFilter jad_mx;
    public static final Float jad_mz;
    public static final PointF jad_na;
    public static final Integer[] jad_ny;
    public static final com.jd.ad.sdk.jad_yh.jad_dq jad_ob;
    public static final Typeface jad_oz;
    public static final Bitmap jad_pa;
    public static final Float jad_pc;
    public static final Float jad_qd;
    public static final Float jad_re;
    public static final Float jad_sf;
    public static final Float jad_tg;
    public static final Float jad_uh;
    public static final Float jad_vi;
    public static final Float jad_wj;
    public static final Float jad_xk;
    public static final Float jad_yl;
    public static final Float jad_zm;
    public static final Integer jad_an = 1;
    public static final Integer jad_bo = 2;
    public static final Integer jad_cp = 3;
    public static final Integer jad_dq = 4;
    public static final Integer jad_er = 5;
    public static final PointF jad_fs = new PointF();
    public static final PointF jad_jt = new PointF();

    static {
        Float valueOf = Float.valueOf(15.0f);
        jad_hu = valueOf;
        Float valueOf2 = Float.valueOf(16.0f);
        jad_iv = valueOf2;
        Float valueOf3 = Float.valueOf(17.0f);
        jad_jw = valueOf3;
        jad_kx = new PointF();
        jad_ly = new PointF();
        Float valueOf4 = Float.valueOf(0.0f);
        jad_mz = valueOf4;
        jad_na = new PointF();
        jad_ob = new com.jd.ad.sdk.jad_yh.jad_dq();
        jad_pc = Float.valueOf(1.0f);
        jad_qd = valueOf4;
        jad_re = valueOf4;
        jad_sf = Float.valueOf(2.0f);
        jad_tg = Float.valueOf(3.0f);
        jad_uh = Float.valueOf(4.0f);
        jad_vi = Float.valueOf(5.0f);
        jad_wj = Float.valueOf(6.0f);
        jad_xk = Float.valueOf(7.0f);
        jad_yl = Float.valueOf(8.0f);
        jad_zm = Float.valueOf(9.0f);
        jad_cn = Float.valueOf(10.0f);
        jad_do = Float.valueOf(11.0f);
        jad_ep = Float.valueOf(12.0f);
        jad_fq = Float.valueOf(12.1f);
        jad_gr = Float.valueOf(13.0f);
        jad_hs = Float.valueOf(14.0f);
        jad_it = valueOf;
        jad_ju = valueOf2;
        jad_kv = valueOf3;
        jad_lw = Float.valueOf(18.0f);
        jad_mx = new ColorFilter();
        jad_ny = new Integer[0];
        jad_oz = Typeface.DEFAULT;
        jad_pa = Bitmap.createBitmap(1, 1, Bitmap.Config.ALPHA_8);
    }
}
