package com.kwad.sdk.core.a.kwai;

import com.ksad.annotation.invoker.InvokeBy;
import com.kwad.components.core.webview.a.kwai.h;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.aa;
import com.kwad.components.core.webview.jshandler.ad;
import com.kwad.components.core.webview.jshandler.ae;
import com.kwad.components.core.webview.jshandler.af;
import com.kwad.components.core.webview.jshandler.ai;
import com.kwad.components.core.webview.jshandler.aj;
import com.kwad.components.core.webview.jshandler.ak;
import com.kwad.components.core.webview.jshandler.al;
import com.kwad.components.core.webview.jshandler.ao;
import com.kwad.components.core.webview.jshandler.ar;
import com.kwad.components.core.webview.jshandler.as;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.av;
import com.kwad.components.core.webview.jshandler.b;
import com.kwad.components.core.webview.jshandler.c;
import com.kwad.components.core.webview.jshandler.d;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.m;
import com.kwad.components.core.webview.jshandler.o;
import com.kwad.components.core.webview.jshandler.w;
import com.kwad.components.core.webview.jshandler.x;
import com.kwad.components.core.webview.jshandler.z;
import com.kwad.components.core.webview.kwai.a;
import com.kwad.components.splash.SplashPreloadManager;
import com.kwad.components.splash.monitor.SplashMonitorInfo;
import com.kwad.sdk.g.a;
import com.kwad.sdk.g.b;

/* loaded from: classes2.dex */
public final class by {
    @InvokeBy(invokerClass = ev.class, methodId = "registerHolder")
    public static void vO() {
        ev.vP().put(com.kwad.components.core.webview.kwai.c.class, new fy());
        ev.vP().put(com.kwad.sdk.kwai.kwai.kwai.a.class, new ek());
        ev.vP().put(a.b.class, new ed());
        ev.vP().put(com.kwad.components.core.webview.a.a.n.class, new fx());
        ev.vP().put(com.kwad.components.core.webview.a.a.w.class, new ja());
        ev.vP().put(ao.a.class, new fb());
        ev.vP().put(com.kwad.components.core.webview.a.a.f.class, new bm());
        ev.vP().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new w());
        ev.vP().put(a.b.class, new co());
        ev.vP().put(com.kwad.components.core.webview.a.a.t.class, new hp());
        ev.vP().put(com.kwad.components.core.webview.a.a.q.class, new gk());
        ev.vP().put(com.kwad.components.core.offline.b.class, new fv());
        ev.vP().put(h.b.class, new gm());
        ev.vP().put(ae.b.class, new dw());
        ev.vP().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new ew());
        ev.vP().put(com.kwad.components.core.webview.a.a.j.class, new et());
        ev.vP().put(m.a.class, new ij());
        ev.vP().put(o.a.class, new q());
        ev.vP().put(com.kwad.components.core.i.a.class, new p());
        ev.vP().put(com.kwad.components.core.webview.a.a.z.class, new jh());
        ev.vP().put(a.C0227a.class, new cr());
        ev.vP().put(com.kwad.components.core.webview.a.a.u.class, new hq());
        ev.vP().put(ak.a.class, new aq());
        ev.vP().put(x.a.class, new go());
        ev.vP().put(b.a.class, new hi());
        ev.vP().put(a.C0196a.class, new cl());
        ev.vP().put(ai.a.class, new gd());
        ev.vP().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new x());
        ev.vP().put(com.kwad.components.core.webview.a.a.e.class, new bf());
        ev.vP().put(w.a.class, new gn());
        ev.vP().put(com.kwad.components.core.webview.a.a.r.class, new hm());
        ev.vP().put(z.a.class, new jb());
        ev.vP().put(com.kwad.components.core.webview.a.a.h.class, new cf());
        ev.vP().put(WebCardVideoPositionHandler.VideoPosition.class, new jg());
        ev.vP().put(com.kwad.components.core.webview.a.a.b.class, new as());
        ev.vP().put(at.a.class, new dy());
        ev.vP().put(com.kwad.components.core.webview.a.a.a.class, new m());
        ev.vP().put(as.a.class, new ip());
        ev.vP().put(com.kwad.components.core.webview.a.a.s.class, new ho());
        ev.vP().put(af.b.class, new es());
        ev.vP().put(com.kwad.components.core.webview.a.a.o.class, new gb());
        ev.vP().put(al.a.class, new ax());
        ev.vP().put(b.C0228b.class, new hj());
        ev.vP().put(c.a.class, new dp());
        ev.vP().put(d.a.class, new dq());
        ev.vP().put(e.b.class, new ds());
        ev.vP().put(com.kwad.components.core.webview.a.a.v.class, new ib());
        ev.vP().put(av.a.class, new eu());
        ev.vP().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new v());
        ev.vP().put(com.kwad.components.core.webview.a.a.i.class, new du());
        ev.vP().put(h.b.class, new ej());
        ev.vP().put(SplashMonitorInfo.class, new ia());
        ev.vP().put(com.kwad.components.core.webview.a.a.l.class, new ez());
        ev.vP().put(aj.a.class, new ao());
        ev.vP().put(b.a.class, new Cdo());
        ev.vP().put(com.kwad.components.core.webview.a.a.y.class, new je());
        ev.vP().put(aa.a.class, new ea());
        ev.vP().put(ak.b.class, new ar());
        ev.vP().put(SplashPreloadManager.PreLoadItem.class, new gs());
        ev.vP().put(ad.a.class, new cb());
        ev.vP().put(com.kwad.components.core.webview.kwai.b.class, new fw());
        ev.vP().put(h.a.class, new ei());
        ev.vP().put(g.a.class, new dt());
        ev.vP().put(af.a.class, new er());
        ev.vP().put(e.a.class, new dr());
        ev.vP().put(com.kwad.components.core.webview.a.a.p.class, new gi());
        ev.vP().put(com.kwad.components.core.webview.a.a.m.class, new fl());
        ev.vP().put(com.kwad.components.core.webview.a.a.c.class, new au());
        ev.vP().put(com.kwad.components.core.webview.a.a.g.class, new bp());
        ev.vP().put(ar.a.class, new ji());
        ev.vP().put(com.kwad.components.core.webview.a.a.d.class, new aw());
        ev.vP().put(com.kwad.components.core.webview.a.a.x.class, new jc());
    }
}
