package com.kwad.sdk.core.config;

import com.bytedance.sdk.openadsdk.downloadnew.core.TTDownloadField;
import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.e;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import java.util.ArrayList;

/* loaded from: classes2.dex */
public final class c {
    public static k abH = new k("batchReportCatchLimit", 20);
    public static k abI = new k("exceptionCollectorSwitch", 1);
    public static k abJ = new k("mediaPlayerLogReport", 0);
    public static k abK = new k("didCopySwitch", 1);
    public static k abL = new k("enableHodor", 0);
    public static k abM = new k("speedLimitSwitch", 1);
    public static k abN = new k("speedLimitThreshold", 200);
    public static k abO = new k("ksNativeAdCustomSwitch", 0);
    public static k abP = new k("forceActivateAfterInstalled", 0);
    public static k abQ = new k("spliceVideoInteractionType", 0);
    public static k abR = new k("formAdExitInterceptSwitch", 0);
    public static k abS = new k("adLeaveConfirmSwitch", 0);
    public static k abT = new k("viewLandingPageTaskDuration", 15);
    public static k abU = new k("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d abV = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static m abW = new m("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d abX = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d abY = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static k abZ = new k("commercialLoggerSwitch", 1);
    public static p aca = new p("tkSoUrlV7a", "");
    public static p acb = new p("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d acc = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static l acd = new l("playerConfig", null);
    public static q ace = new q("pkgNameList", new ArrayList(0));
    public static q acf = new q("hostList", new ArrayList(0));
    public static q acg = new q("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem ach = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c aci = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem acj = new InstallActivateReminderConfigItem();
    public static e ack = new e();
    public static n acl = new n("realtimeReportActions", "");
    public static o acm = new o();
    public static k acn = new k("appInstallNoticeSecond", 0);
    public static k aco = new k("installFloatingLayerPostion", 0);
    public static k acp = new k("remindInstallStyle", 0);
    public static k acq = new k("remindInstallTime", 60);
    public static k acr = new k("watermarkKwaiIdSwitch", 0);
    public static k acs = new k("insertScreenV2Switch", 0);
    public static k act = new k("insertScreenAutoPlaySwitch", 0);
    public static j acu = new j("insertScreenV2ShowConfig");
    public static k acv = new k("environmentDetectEnable", 0);
    public static k acw = new k("simCardInfoEnable", 0);
    public static k acx = new k("baseStationEnable", 0);
    public static k acy = new k("sensorEventEnable2", 0);
    public static k acz = new k("lpAutoDownloadApkSwitch", 1);
    public static k acA = new k("autoDownloadUrlSwitch", 0);
    public static k acB = new k("insertScreenAdType", 0);
    public static k acC = new k("interstitialAutoCallAppCountDaily", 1);
    public static k acD = new k("mediaControlPlaySwitch", 1);
    public static p acE = new p("appStatusSoUrlV7a", "");
    public static p acF = new p("appStatusSoUrlV8a", "");
    public static p acG = new p("appStatusSoVersion", "");
    public static k acH = new k("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d acI = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static h acJ = new h();
    public static com.kwad.sdk.core.config.item.d acK = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d acL = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static com.kwad.sdk.core.config.item.d acM = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d acN = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d acO = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static k acP = new k("forceActivate", 0);
    public static k acQ = new k("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d acR = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static k acS = new k("enableAnrReportReal", 0);
    public static k acT = new k("enableNativeCrashReport", 0);
    public static p acU = new p("exceptionSoUrlV7a", "");
    public static p acV = new p("exceptionSoUrlV8a", "");
    public static k acW = new k("kwaiAppVersionSwitch", 1);
    public static p acX = new p(TTDownloadField.TT_USERAGENT, com.kwad.sdk.core.network.q.getDefaultUserAgent());
    public static k acY = new k("biddingLogSwitch", 0);
    public static k acZ = new k("forceActiveThreshold", 5);
    public static k ada = new k("forceActiveInterval", 3);
    public static k adb = new k("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d adc = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static g add = new g("adExposureAreaPercent", 0.3f);
    public static g ade = new g("adExposureTime", -1.0f);
    public static g adf = new g("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d adg = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d adh = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static k adi = new k("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d adj = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static k adk = new k("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d adl = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d adm = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static m adn = new m("obiwanLogFilesDiskQuota", 52428800L);
    public static l ado = new l("logCommandResult", "", false);
    public static m adp = new m("validClickConvertTime", 1000L);
    public static k adq = new k("playableAutoPlayEnable", 1);
    public static k adr = new k("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d ads = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d adt = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static k adu = new k("weaponSwitch", 1);
    public static k adv = new k("kvModeV2", 0);
    public static i adw = new i();
    public static m adx = new m("currentServerTimeMs");
    public static k ady = new k("clientProofreadTimeErrorRangeHours", 100);
    public static g adz = new g("adTraceReportRate", 1.0f);
    public static k adA = new k("adTraceRepeatEnable", 0);
    public static k adB = new k("appHeartBeatInterval", 0);
    public static k adC = new k("adCacheCode", 0);
    public static p adD = new p("installTipsContentDesc", "");
    public static p adE = new p("installTipsPositiveActionDesc", "");
    public static p adF = new p("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d adG = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static p adH = new p("perfMonitorV2", "");
    public static k adI = new k("neoVideoAdaptStrategy", 1);
    public static com.kwad.sdk.core.config.item.d adJ = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static com.kwad.sdk.core.config.item.d adK = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static p adL = new p("ranger", "");
    public static p adM = new p("threadPoolPerfMonitor", "");
    public static p adN = new p("threadPoolParams", "");
    public static f adO = new f("crashUploadRate", Double.valueOf(1.0d));
    public static com.kwad.sdk.core.config.item.d adP = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d adQ = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);

    public static void init() {
    }
}
